output "ec2_public_ip" {
  value = module.ec2.ec2_public_ip
}

output "ec2_public_dns" {
  value = module.ec2.ec2_public_dns
}

output "db_endpoint" {
  value = module.db.db_endpoint
}

output "memcached_endpoint" {
  value = module.memcached.memcached_endpoint
}

output "s3_endpoint" {
  value = module.s3.s3_endpoint
}

output "secret_key" {
  sensitive = true
  value     = module.iam.secret_key
}

output "access_key" {
  value = module.iam.access_key
}

# Export Terraform variable values to an Ansible var_file
resource "local_file" "tf_ansible_vars_file_new" {
  content = <<-DOC
    # Ansible vars_file containing variable values from Terraform.
    # Generated by Terraform mgmt configuration.

    tf_db_endpoint: ${module.db.db_endpoint}
    tf_memcached_endpoint: ${module.memcached.memcached_endpoint}
    tf_s3_endpoint: ${module.s3.s3_endpoint}
    tf_access_key: ${module.iam.access_key}
    tf_secret_key: ${module.iam.secret_key}
    DOC
  filename = "../ansible/vars/tf_ansible_vars_file.yml"
}

 resource "local_file" "ansible_inventory" {
  content = templatefile("./templates/hosts.tpl",
    {
      public_ips = module.ec2.ec2_public_ip.*,
    }
  )
  filename = "../ansible/hosts"
 }